services:
  ocserv:
    image: cherts/ocserv:latest
    restart: always
    container_name: ocserv
    privileged: true
    hostname: vpn.myorg.com
    ports:
      - 443:443/udp
      - 443:443/tcp
    volumes:
      - type: bind
        source: ${PWD}/ocpasswd
        target: /etc/ocserv/ocpasswd
    environment:
      - HC_CA_CN=My CA
      - HC_CA_ORG=My Corp
      - HC_CA_DAYS=3650
      - HC_SRV_CN=vpn.myorg.com
      - HC_SRV_ORG=My Org
      - HC_SRV_DAYS=365
      - HC_NO_TEST_USER=1
#      - HC_NO_CREATE_DH_PARAMS=1
#      - HC_NO_CREATE_SERVER_CERT=1
#      - HC_TCP_PORT=8443
#      - HC_UDP_PORT=8443
#      - HC_WORKDIR=/opt/ocserv
#      - HC_OTHER_OPTS=-d 9
