services:
  ocserv:
    image: cherts/ocserv:latest
    restart: always
    container_name: ocserv
    privileged: true
    hostname: vpn.myorg.com
    ports:
      - 8443:8443/udp
      - 8443:8443/tcp
    volumes:
      - type: bind
        source: ${PWD}/config
        target: /etc/ocserv
    environment:
      - HC_CA_CN=My CA
      - HC_CA_ORG=My Corp
      - HC_CA_DAYS=3650
      - HC_SRV_CN=vpn.myorg.com
      - HC_SRV_ORG=My Org
      - HC_SRV_DAYS=365
      - HC_NO_TEST_USER=1
      - HC_TCP_PORT=8443
      - HC_UDP_PORT=8443
