#!/bin/ash

CONF_DIR=${HC_WORKDIR:-"/etc/ocserv"}
MODE=${1}
USER=${2}

if [ -z "$USER" ]; then
	echo "ERROR: Use $0 <create|delete|lock|unlock> <username>"
	exit 1;
fi

case "$MODE" in
	"create")
		FLAG='';
		;;
	"delete")
		FLAG='-d';
		;;
	"lock")
		FLAG='-l';
		;;
	"unlock")
		FLAG='-u';
		;;
	*)
		echo "ERROR: Use $0 <create|delete|lock|unlock> <username>"
		exit 1
		;;
esac

if [ -f "${CONF_DIR}/ocpasswd" ]; then
	if [ -f "${CONF_DIR}/ocpasswd.tmp" ]; then
		echo "WARNING: File '${CONF_DIR}/ocpasswd' is locked. Unlock..."
		rm -f "${CONF_DIR}/ocpasswd.tmp" >/dev/null 2>&1
	fi
	ocpasswd -c "${CONF_DIR}/ocpasswd" ${FLAG} "${USER}"
else
	echo "ERROR: Password file '${CONF_DIR}/ocpasswd' not found."
	exit 1
fi
