---
name: Default

on:
  push:
    paths:
      - "config/**"
      - "scripts/**"
      - "Dockerfile"
      - "build.sh"
  pull_request:
    paths:
      - "config/**"
      - "scripts/**"
      - "Dockerfile"
      - "build.sh"

jobs:
  ocserv:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "HC_VERSION=1.3.0" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image cherts/ocserv:${{ env.HC_VERSION }}
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          file: ./Dockerfile
          platforms: linux/amd64
          tags: cherts/ocserv:latest,cherts/ocserv:${{ env.HC_VERSION }}
      - name: Inspect image cherts/ocserv:${{ env.HC_VERSION }}
        run: |
          docker image inspect cherts/ocserv:${{ env.HC_VERSION }}
      - name: Test image cherts/ocserv:${{ env.HC_VERSION }}
        run: |
          docker run --rm --name ocserv cherts/ocserv:${{ env.HC_VERSION }} --version
