name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v1.*"

jobs:
  Build:
    name: Build-Docker
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "HC_VERSION=1.3.0" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Build and push image cherts/ocserv:${{ env.HC_VERSION }}
        uses: docker/build-push-action@v5
        with:
          push: true
          cache-from: type=gha,scope=ocserv
          cache-to: type=gha,mode=max,scope=ocserv
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: cherts/ocserv:latest,cherts/ocserv:${{ env.HC_VERSION }}
